// commitlint config — enforces Conventional Commits.
// Each non-default rule has a `// why:` line directly above it.
// Project policy: no rule disabled without rationale.

module.exports = {
  extends: ['@commitlint/config-conventional'],

  // why: merge commits are generated by `git merge`, not authored, so they
  // can't be Conventional Commits — they'd fail `type-empty` +
  // `subject-empty` forever and poison every `bb ci` run whose HEAD~20
  // window happens to contain one. commitlint's `defaultIgnores` only skips
  // `Merge branch` / `Merge pull request` / `Merge remote-tracking`; this
  // repo also writes `Merge feature/<name>: <summary>`, which slips through.
  // A real commit never starts with `Merge ` (Conventional Commits open with
  // `<type>(<scope>):`), so matching on the prefix is precise enough.
  ignores: [(message) => /^Merge\b/.test(message)],

  rules: {
    // why: Conventional Commits default caps body lines at 100; this
    // repo writes prose-heavy commit bodies (architectural decisions,
    // lessons learned), wrapping at ~72 for `git log` readability.
    // Bump cap to 200 so long URLs / quoted error messages aren't
    // split mid-word.
    'body-max-line-length': [2, 'always', 200],

    // why: same as body — footers carry Co-Authored-By lines +
    // occasional URLs; 200 covers both.
    'footer-max-line-length': [2, 'always', 200],

    // why: permit any case in subject — graphden mixes lowercase
    // prose ('feat(editor):') with proper-noun caps ('docs(README)')
    // depending on what reads cleaner.
    'subject-case': [0],

    // why: default Conventional Commits types + a few graphden uses
    // already (`skill` for .claude/skills/ edits). Enumerated
    // explicitly so the linter recognises them.
    'type-enum': [2, 'always', [
      'build', 'chore', 'ci', 'docs', 'feat', 'fix', 'perf', 'refactor',
      'revert', 'style', 'test', 'skill',
    ]],
  },
};
