;;; devtour.el --- guided read of the graphden codebase  -*- lexical-binding: t; -*-

;; Author: graphden
;; Package-Requires: ((emacs "27.1"))
;; Keywords: tools, docs

;;; Commentary:

;; The developer code-tour, driving your editor instead of a browser.
;;
;; `docs/devtour/index.html' bakes a snapshot of each anchored form; this mode
;; shows you the LIVE file at that form instead, so everything you would do
;; next — `xref-find-references', grep, magit, the REPL — is one keystroke away
;; and can never disagree with what the tour is pointing at.
;;
;;   M-x devtour            start (or resume where you stopped)
;;   M-x devtour-here       open the tour at the form point is in
;;   M-x devtour-goto       jump to any step by name or prose
;;
;; In the *devtour* window: n/p walk the spine, b goes back along the path you
;; actually took, s follows a see-also link, g lists the blocks, o moves point
;; into the source, q quits.
;;
;; `devtour-annotate-mode' is the other direction: a global minor mode that
;; makes eldoc say "Types, step 4/17 — <why this form matters>" whenever point
;; sits in a form the tour covers.
;;
;; Setup:
;;
;;   (load "/path/to/graphden/docs/devtour/devtour.el")
;;   (devtour-annotate-mode 1)   ; optional
;;
;; The data file (`tour.eld') is regenerated by `bb devtour' and drift-checked
;; by CI, so an anchor here can never point at code that was renamed away.
;; To read the Russian tour instead, point `devtour-data-file' at its bake.

;;; Code:

(require 'cl-lib)
(require 'subr-x)

(defgroup devtour nil
  "Guided read of the graphden codebase."
  :group 'tools
  :prefix "devtour-")

(defconst devtour--here
  (file-name-directory (or load-file-name buffer-file-name default-directory))
  "Directory this file was loaded from.")

(defcustom devtour-data-file (expand-file-name "tour.eld" devtour--here)
  "Baked tour data (`bb devtour' writes it next to index.html)."
  :type 'file)

(defcustom devtour-repo-root
  (expand-file-name "../../" devtour--here)
  "Checkout the step anchors are relative to."
  :type 'directory)

(defcustom devtour-progress-file
  (locate-user-emacs-file "devtour-progress.eld")
  "Where reading progress is remembered."
  :type 'file)

(defcustom devtour-window-width 68
  "Width of the prose side window."
  :type 'integer)

(defcustom devtour-fill-column 72
  "Column the prose is filled to."
  :type 'integer)

(defface devtour-title '((t :inherit font-lock-function-name-face :weight bold :height 1.1))
  "Face for the step title.")
(defface devtour-meta '((t :inherit shadow))
  "Face for the crumb / metadata lines.")
(defface devtour-code '((t :inherit font-lock-constant-face))
  "Face for `inline code' in tour prose.")
(defface devtour-strong '((t :weight bold))
  "Face for **bold** in tour prose.")

;;; --- data -------------------------------------------------------------------

(defvar devtour--tour nil "Parsed `devtour-data-file'.")
(defvar devtour--steps nil "Vector of step plists, in spine order.")
(defvar devtour--by-key nil "Hash of step key -> spine position.")
(defvar devtour--pos nil "Current spine position.")
(defvar devtour--history nil "Visited positions, most recent first.")
(defvar devtour--seen nil "Hash of step key -> t.")
(defvar devtour--last nil "Key of the last step visited in an earlier session.")

(defun devtour--load ()
  "Read the tour data and progress once."
  (unless devtour--steps
    (unless (file-readable-p devtour-data-file)
      (user-error "devtour: no data at %s (run `bb devtour')" devtour-data-file))
    (setq devtour--tour
          (with-temp-buffer
            (insert-file-contents devtour-data-file)
            (read (current-buffer))))
    (let ((steps '()))
      (dolist (block (plist-get devtour--tour :blocks))
        (dolist (step (plist-get block :steps))
          (push (append step (list :block-id (plist-get block :id)
                                   :block-title (plist-get block :title)
                                   :block-n (length (plist-get block :steps))))
                steps)))
      (setq devtour--steps (vconcat (nreverse steps))))
    (setq devtour--by-key (make-hash-table :test 'equal))
    (dotimes (i (length devtour--steps))
      (puthash (plist-get (aref devtour--steps i) :key) i devtour--by-key))
    (devtour--load-progress))
  devtour--steps)

(defun devtour--load-progress ()
  (setq devtour--seen (make-hash-table :test 'equal))
  (when (file-readable-p devtour-progress-file)
    (ignore-errors
      (let ((data (with-temp-buffer
                    (insert-file-contents devtour-progress-file)
                    (read (current-buffer)))))
        (dolist (k (plist-get data :seen)) (puthash k t devtour--seen))
        (setq devtour--last (plist-get data :last))))))

(defun devtour--save-progress ()
  (let ((keys '()))
    (maphash (lambda (k _) (push k keys)) devtour--seen)
    (ignore-errors
      (with-temp-file devtour-progress-file
        (prin1 (list :seen (sort keys #'string<)
                     :last (or devtour--last ""))
               (current-buffer))
        (insert "\n")))))

(defun devtour--step (&optional pos)
  (aref devtour--steps (or pos devtour--pos)))

(defun devtour--label (step)
  (format "%s › %s" (plist-get step :block-title) (plist-get step :defn)))

;;; --- prose rendering --------------------------------------------------------

(defun devtour--render-markdown (start)
  "Fontify the tour's tiny markdown between START and point-max."
  (save-excursion
    (goto-char start)
    (while (re-search-forward "`\\([^`\n]+\\)`" nil t)
      (replace-match (propertize (match-string 1) 'face 'devtour-code) t t))
    (goto-char start)
    (while (re-search-forward "\\*\\*\\([^*\n]+\\)\\*\\*" nil t)
      (replace-match (propertize (match-string 1) 'face 'devtour-strong) t t))
    (goto-char start)
    (while (re-search-forward "\\[\\([^]\n]+\\)\\](\\([^)\n]+\\))" nil t)
      (replace-match (propertize (match-string 1) 'face 'link) t t))))

(defun devtour--render (step)
  "Fill the *devtour* buffer with STEP."
  (with-current-buffer (get-buffer-create "*devtour*")
    (let ((inhibit-read-only t))
      (erase-buffer)
      (devtour-mode)
      (insert (propertize (format "%s\n" (plist-get step :defn)) 'face 'devtour-title))
      (insert (propertize
               (format "%s · step %d/%d · spine %d/%d · ~%s min\n%s:%d\n\n"
                       (plist-get step :block-title)
                       (plist-get step :n) (plist-get step :block-n)
                       (1+ devtour--pos) (length devtour--steps)
                       (plist-get step :mins)
                       (plist-get step :file) (plist-get step :line))
               'face 'devtour-meta))
      (let ((start (point))
            (fill-column devtour-fill-column))
        (insert (plist-get step :say) "\n")
        (fill-region start (point-max))
        (devtour--render-markdown start))
      (dolist (pair (list (cons "see also" (plist-get step :see))
                          (cons "referenced from" (plist-get step :refs))
                          (cons "same file" (plist-get step :siblings))))
        (when (cdr pair)
          (insert (propertize (format "\n%s: %s\n" (car pair)
                                      (mapconcat #'cdr (cdr pair) ", "))
                              'face 'devtour-meta))))
      (insert (propertize "\n[n]ext [p]rev [b]ack [s]ee-also [g]index [o]source [q]uit\n"
                          'face 'devtour-meta))
      (goto-char (point-min))
      (setq buffer-read-only t))
    (current-buffer)))

;;; --- source window ----------------------------------------------------------

(defun devtour--visit (step)
  "Show STEP's live source, positioned on the anchored form."
  (let* ((path (expand-file-name (plist-get step :file) devtour-repo-root))
         (head (plist-get step :head)))
    (unless (file-readable-p path)
      (user-error "devtour: %s is not in %s" (plist-get step :file) devtour-repo-root))
    (let ((buf (find-file-noselect path)))
      (with-current-buffer buf
        (goto-char (point-min))
        (forward-line (1- (plist-get step :line)))
        ;; The baked line is a hint; the head line is the anchor, exactly like
        ;; the generator's symbol lookup — so an edit above the form is harmless.
        (unless (looking-at-p (regexp-quote head))
          (let ((found (save-excursion
                         (goto-char (point-min))
                         (search-forward head nil t))))
            (if found
                (progn (goto-char found) (beginning-of-line))
              (message "devtour: anchor `%s' not found in %s — run `bb devtour'"
                       head (plist-get step :file)))))
        (when (fboundp 'pulse-momentary-highlight-one-line)
          (pulse-momentary-highlight-one-line (point))))
      buf)))

(defun devtour--show (pos &optional push)
  "Render spine position POS in both windows."
  (devtour--load)
  (setq pos (max 0 (min pos (1- (length devtour--steps)))))
  (when (and push devtour--pos (/= pos devtour--pos))
    (push devtour--pos devtour--history))
  (setq devtour--pos pos)
  (let* ((step (devtour--step))
         (src (devtour--visit step))
         (prose (devtour--render step)))
    (puthash (plist-get step :key) t devtour--seen)
    (setq devtour--last (plist-get step :key))
    (devtour--save-progress)
    (pop-to-buffer src '(display-buffer-same-window))
    (display-buffer-in-side-window
     prose `((side . right) (window-width . ,devtour-window-width)
             (dedicated . t)))
    (select-window (get-buffer-window prose))
    (recenter-top-bottom 0)
    step))

;;; --- commands ---------------------------------------------------------------

;;;###autoload
(defun devtour (&optional arg)
  "Start the developer code-tour, resuming where you stopped.
With prefix ARG, start from the first step instead."
  (interactive "P")
  (devtour--load)
  (let ((pos (or (and (not arg) devtour--last
                      (gethash devtour--last devtour--by-key))
                 0)))
    (devtour--show pos)
    (message "devtour: %d steps, ~%.1f h — n/p walk, ? for keys"
             (length devtour--steps) (/ (plist-get devtour--tour :mins) 60.0))))

(defun devtour-next ()
  "Next step along the spine."
  (interactive)
  (devtour--show (1+ devtour--pos) t))

(defun devtour-previous ()
  "Previous step along the spine."
  (interactive)
  (devtour--show (1- devtour--pos) t))

(defun devtour-back ()
  "Back along the path you actually took."
  (interactive)
  (if-let ((prev (pop devtour--history)))
      (devtour--show prev)
    (user-error "devtour: no history")))

(defun devtour--completing-read (prompt steps)
  "Pick one of STEPS by label, prose included in the annotation."
  (let* ((width (max 34 (/ (frame-width) 3)))
         (cands (mapcar
                 (lambda (i)
                   (let* ((s (aref devtour--steps i))
                          (say (replace-regexp-in-string
                                "[`*]" "" (plist-get s :say))))
                     (cons (concat
                            (truncate-string-to-width (devtour--label s) width 0 ?\s)
                            "  " (truncate-string-to-width say 120))
                           i)))
                 steps))
         (pick (completing-read prompt cands nil t)))
    (cdr (assoc pick cands))))

(defun devtour-goto ()
  "Jump to any step, searching names, blocks and prose."
  (interactive)
  (devtour--load)
  (devtour--show (devtour--completing-read
                  "Step: " (number-sequence 0 (1- (length devtour--steps))))
                 t))

(defun devtour-see-also ()
  "Follow one of this step's see-also / referenced-from / same-file links."
  (interactive)
  (let* ((step (devtour--step))
         (links (append (plist-get step :see) (plist-get step :refs)
                        (plist-get step :siblings))))
    (unless links (user-error "devtour: no links on this step"))
    (let* ((pick (if (cdr links)
                     (completing-read "Link: " (mapcar #'cdr links) nil t)
                   (cdr (car links))))
           (key (car (cl-find pick links :key #'cdr :test #'equal))))
      (devtour--show (gethash key devtour--by-key) t))))

(defun devtour-index ()
  "Pick a block, then its first step."
  (interactive)
  (devtour--load)
  (let* ((blocks (cl-remove-if-not
                  (lambda (b) (equal "toured" (plist-get b :status)))
                  (plist-get devtour--tour :blocks)))
         (cands (mapcar (lambda (b)
                          (cons (format "%-46s %2d steps · ~%d min"
                                        (plist-get b :title)
                                        (length (plist-get b :steps))
                                        (round (plist-get b :mins)))
                                (plist-get (car (plist-get b :steps)) :key)))
                        blocks))
         (pick (completing-read "Block: " cands nil t)))
    (devtour--show (gethash (cdr (assoc pick cands)) devtour--by-key) t)))

(defun devtour-source ()
  "Move point into the source window."
  (interactive)
  (let ((buf (get-file-buffer
              (expand-file-name (plist-get (devtour--step) :file) devtour-repo-root))))
    (when buf (select-window (get-buffer-window buf)))))

(defun devtour-quit ()
  "Close the prose window."
  (interactive)
  (when-let ((w (get-buffer-window "*devtour*")))
    (quit-window nil w)))

(defun devtour-reset-progress ()
  "Forget which steps have been read."
  (interactive)
  (devtour--load)
  (clrhash devtour--seen)
  (setq devtour--last nil)
  (devtour--save-progress)
  (message "devtour: progress cleared"))

(defun devtour-progress ()
  "Report how much of the tour has been read."
  (interactive)
  (devtour--load)
  (let ((n (hash-table-count devtour--seen))
        (total (length devtour--steps)))
    (message "devtour: %d/%d steps (%d%%)" n total
             (if (zerop total) 0 (round (* 100.0 (/ (float n) total)))))))

;;; --- the reverse direction: tour annotations in ordinary buffers ------------

(defun devtour--steps-for-file (file)
  "Steps anchored in FILE (repo-relative), sorted by line."
  (devtour--load)
  (sort (cl-remove-if-not
         (lambda (s) (equal file (plist-get s :file)))
         (append devtour--steps nil))
        (lambda (a b) (< (plist-get a :line) (plist-get b :line)))))

(defun devtour--relative-name ()
  (when buffer-file-name
    (let ((rel (file-relative-name buffer-file-name devtour-repo-root)))
      (unless (string-prefix-p ".." rel) rel))))

(defun devtour-step-at-point ()
  "The tour step covering point, or nil.
A step covers from its own anchor line up to the next anchored form in
the same file — close enough to name the form you are looking at."
  (when-let ((rel (devtour--relative-name)))
    (let ((line (line-number-at-pos))
          (hit nil))
      (dolist (s (devtour--steps-for-file rel))
        (when (<= (plist-get s :line) line) (setq hit s)))
      hit)))

(defun devtour-here ()
  "Open the tour at the step covering point."
  (interactive)
  (let ((s (or (devtour-step-at-point)
               (user-error "devtour: nothing here is toured"))))
    (devtour--show (gethash (plist-get s :key) devtour--by-key) t)))

(defun devtour--eldoc (callback &rest _)
  "Eldoc function reporting the tour step covering point."
  (when-let ((s (devtour-step-at-point)))
    (funcall callback
             (format "devtour · %s %d/%d: %s"
                     (plist-get s :block-title) (plist-get s :n) (plist-get s :block-n)
                     (truncate-string-to-width
                      (replace-regexp-in-string "[`*]" "" (plist-get s :say)) 160))
             :thing (plist-get s :defn)
             :face 'devtour-meta)
    t))

;;;###autoload
(define-minor-mode devtour-annotate-mode
  "Let eldoc say which tour step covers the form at point."
  :global t :lighter " Tour"
  (if devtour-annotate-mode
      (add-hook 'eldoc-documentation-functions #'devtour--eldoc 90)
    (remove-hook 'eldoc-documentation-functions #'devtour--eldoc)))

;;; --- org-protocol: the HTML page's "open in emacs" button -------------------

;;;###autoload
(defun devtour-org-protocol-open (info)
  "Open the file named by INFO (:file repo-relative, :line) in this emacs."
  (let* ((file (plist-get info :file))
         (line (string-to-number (or (plist-get info :line) "1")))
         (path (expand-file-name file devtour-repo-root)))
    (if (not (file-readable-p path))
        (message "devtour: no such file %s" path)
      (find-file path)
      (goto-char (point-min))
      (forward-line (1- line))
      (recenter 0)
      (when (fboundp 'pulse-momentary-highlight-one-line)
        (pulse-momentary-highlight-one-line (point)))
      (select-frame-set-input-focus (selected-frame))))
  nil)

(with-eval-after-load 'org-protocol
  (add-to-list 'org-protocol-protocol-alist
               '("devtour" :protocol "devtour" :function devtour-org-protocol-open)))

;;; --- mode -------------------------------------------------------------------

(defvar devtour-mode-map
  (let ((m (make-sparse-keymap)))
    (define-key m "n" #'devtour-next)
    (define-key m "p" #'devtour-previous)
    (define-key m "b" #'devtour-back)
    (define-key m "s" #'devtour-see-also)
    (define-key m "g" #'devtour-index)
    (define-key m "/" #'devtour-goto)
    (define-key m "o" #'devtour-source)
    (define-key m "q" #'devtour-quit)
    (define-key m "?" #'describe-mode)
    (define-key m (kbd "SPC") #'devtour-next)
    (define-key m (kbd "DEL") #'devtour-previous)
    m)
  "Keymap for `devtour-mode'.")

(define-derived-mode devtour-mode special-mode "Devtour"
  "Major mode for the tour's prose pane.

\\{devtour-mode-map}"
  (setq-local truncate-lines nil)
  (visual-line-mode 1))

(provide 'devtour)
;;; devtour.el ends here
