(ns ^:serial graphden.executor.builtin-plans-test
  "Release artifacts must be checked, reproducible package graphs."
  (:require
    [cheshire.core :as json]
    [clojure.edn :as edn]
    [clojure.java.shell :as sh]
    [clojure.test :refer [deftest is testing use-fixtures]]
    [graphden.executor.browser-plan :as plan]
    [graphden.executor.browser-snapshot :as snapshot]
    [graphden.executor.compile-runtime :as runtime]
    [graphden.executor.interface :as exec]
    [graphden.executor.registry.core :as registry]
    [graphden.executor.test-setup :as setup]
    [graphden.packages.owned :as owned]
    [graphden.packages.records.ids :as ids]
    [graphden.storage.protocol.core :as sp]
    [graphden.test-infra.account-menu-cases :as account-menu]
    [graphden.test-infra.browser-picker-cases :as picker]
    [graphden.types.core :as types]
    [graphden.types.core.shapes :as shapes]))


(use-fixtures :once (setup/create-container-fixture) exec/with-isolated-rich-types)


;; Build tooling deliberately stays off the server's production classpath.
(load-file "tools/ui_preview/builtin_plans.clj")


(defn- tool
  [name & args]
  (apply (ns-resolve 'tools.ui-preview.builtin-plans name) args))


(defn- failure
  [f]
  (try (f) nil (catch clojure.lang.ExceptionInfo e (ex-data e))))


(deftest source-fingerprint-preserves-edn-value-identity
  (let [fingerprint #(tool 'source-fingerprint [{:args {:value {:value %}}}] {})]
    (is (not= (fingerprint {:phase 1 ":phase" 2})
              (fingerprint {:phase 3 ":phase" 2})))
    (is (not= (fingerprint #{1 2}) (fingerprint [1 2])))
    (is (= (fingerprint {:a 1 :b 2})
           (binding [*print-length* 1 *print-level* 1]
             (fingerprint {:a 1 :b 2}))))
    (is (= (fingerprint (array-map :a 1 :b 2))
           (fingerprint (array-map :b 2 :a 1))))))


(deftest shipped-builtin-plans-are-reproducible-and-isolated
  (let [rich (atom {:by-id {} :by-name {}})
        aliases (atom {:outside :int})
        markers (atom {:secret {:monotone? true :hide-result? true}})
        id (ids/fn-id "app.ui-account-menu" :account-menu-view)
        package? (owned/owned-fn-id? id)
        package-body (types/package-alias-body :text-map)]
    (binding [registry/*rich-types-override* rich
              types/*type-aliases-override* aliases
              shapes/*marker-registry-override* markers]
      (let [artifact (tool 'generate)
            payload (tool 'serialize artifact)]
        (let [baked (slurp "resources/packages/app/ui-preview/builtin-plans.json")
              script (slurp "resources/packages/app/ui-preview/builtin-plans.js")
              expected-script (str "// Generated by tools/ui_preview/generate_builtin_plans.clj.\n"
                                   "window.GraphdenBuiltinPlans=" payload ";\n")]
          ;; Keep exact byte equality; report hashes instead of dumping the
          ;; complete generated graph and JavaScript into a failed CI log.
          (is (true? (= baked payload))
              (str "Regenerate with clojure -M:dev tools/ui_preview/generate_builtin_plans.clj; "
                   "baked SHA-256=" (ids/digest-hex "SHA-256" baked)
                   "; generated SHA-256=" (ids/digest-hex "SHA-256" payload)
                   "; sourceFingerprint=" (:sourceFingerprint artifact)))
          (is (true? (= script expected-script))
              (str "Builtin JavaScript bytes differ; baked SHA-256=" (ids/digest-hex "SHA-256" script)
                   "; generated SHA-256=" (ids/digest-hex "SHA-256" expected-script))))
        (is (re-matches #"[0-9a-f]{64}" (:sourceFingerprint artifact)))
        (is (= "theme" (get-in artifact [:themeTemplate :rootName])))
        (is (= (mapv #(assoc % :namespace "__GRAPHDEN_THEME_NAMESPACE__")
                     (:fns (edn/read-string (slurp "resources/packages/app/ui-theme-template/fns.edn"))))
               (:fns (edn/read-string (get-in artifact [:themeTemplate :edn])))))
        (is (= #{:accountMenu :fnPicker} (set (keys (:plans artifact)))))
        (doseq [[_ compiled] (:plans artifact)]
          (is (= 1 (:format compiled) (:primitiveAbi compiled)))
          (is (= #{"initial" "update" "view"} (set (keys (:entries compiled)))))))
      (is (= {:by-id {} :by-name {}} @rich))
      (is (= {:outside :int} @aliases))
      (is (= {:secret {:monotone? true :hide-result? true}} @markers)))
    (is (= package? (owned/owned-fn-id? id)))
    (is (= package-body (types/package-alias-body :text-map)))))


(deftest source-errors-and-secret-annotations-veto-generation
  (let [source-var (ns-resolve 'tools.ui-preview.builtin-plans 'source-definitions)
        definitions (source-var)]
    (doseq [[label return-type] [["incompatible declared type" :int]
                                 ["secret annotation erased by storage" [:secret :_account-menu-state]]]]
      (testing label
        (let [changed (mapv #(cond-> % (= :account-menu-initial (:name %))
                                     (assoc :return-type return-type)) definitions)]
          (is (some? (with-redefs-fn {source-var (constantly changed)}
                       #(failure (fn [] (tool 'generate)))))))))
    (testing "concealed source remains forbidden"
      (let [graph-var (ns-resolve 'tools.ui-preview.builtin-plans 'source-graph)
            original @graph-var
            concealed (fn [source]
                        (update-in (original source) [:snapshot :graph :fns]
                                   #(mapv (fn [row]
                                            (cond-> row (= "account-menu-initial" (:name row))
                                                    (assoc :concealed? true))) %)))]
        (is (= :concealed-function
               (:reason (with-redefs-fn {graph-var concealed}
                          #(failure (fn [] (tool 'generate)))))))))
    (testing "CLI cannot turn into an arbitrary source or root exporter"
      (is (some? (failure #(tool '-main "--view" (str (random-uuid)))))))))


(deftest generated-artifacts-run-ordinary-menu-and-picker-cases
  (let [artifact (json/parse-string-strict
                   (slurp "resources/packages/app/ui-preview/builtin-plans.json") true)
        menu-cases (mapv #(update % :entry (fn [entry]
                                             (case entry :account-menu-initial :initial
                                                   :account-menu-update :update
                                                   :account-menu-view :view)))
                         (account-menu/cases))
        picker-cases (mapv #(assoc % :entry :view :operation-limit 100000)
                           (filter #(= :picker-view (:entry %)) picker/cases))]
    (doseq [[kind cases] [[:accountMenu menu-cases] [:fnPicker picker-cases]]]
      (let [request {:plan (get-in artifact [:plans kind])
                     :cases (mapv (fn [{:keys [entry inputs operation-limit]}]
                                    {:entry (name entry) :operationLimit (or operation-limit 10000)
                                     :inputs (into {} (map (fn [[k v]] [(name k) (plan/encode-value v)])) inputs)}) cases)}
            {:keys [exit out err]} (sh/sh "node" "tools/runtime-test/browser-plan-runner.js"
                                          :in (json/generate-string request))]
        (is (zero? exit) err)
        (when (zero? exit)
          (doseq [[expected actual] (map vector cases (json/parse-string-strict out true))]
            (is (nil? (:error actual)) (:error actual))
            (is (= (:expected expected) (some-> (:value actual) plan/decode-value)))))))))


(deftest stored-picker-disabled-state-exports-with-checked-source
  (binding [registry/*rich-types-override* (atom {:by-id {} :by-name {}})
            registry/*per-org-rich-override* (atom {})
            types/*type-aliases-override* (atom {})
            types/*alias-view* nil
            runtime/*per-org-aliases-override* (atom {})]
    (let [{:keys [storage ctx]} (setup/bootstrap-crud-graph-from-golden!)]
      (try
        (let [captured (snapshot/read-snapshot storage)
              policy (tool 'check-source! (tool 'source-definitions) captured storage)
              row-id (ids/fn-id "app.ui-fn-picker" :picker-row)
              value-id (ids/fn-id "app.ui-fn-picker" :_picker-row-disabled-value)
              exported (snapshot/export-snapshot captured {} {:view row-id} policy)
              cases (filterv #(= :picker-row (:entry %)) picker/cases)
              request {:plan exported
                       :cases (mapv (fn [{:keys [inputs]}]
                                      {:entry "view"
                                       :inputs {"row" (plan/encode-value (:row inputs))}}) cases)}
              {:keys [exit out err]} (sh/sh "node" "tools/runtime-test/browser-plan-runner.js"
                                            :in (json/generate-string request))]
          (is (= :plain (get-in policy [:classes value-id])))
          (is (some #(= (str value-id) (:id %)) (:functions exported)))
          (is (zero? exit) err)
          (when (zero? exit)
            (doseq [[{:keys [inputs expected]} actual] (map vector cases (json/parse-string-strict out true))]
              (is (nil? (:error actual)) (:error actual))
              (is (= expected (exec/execute ctx row-id inputs)
                     (some-> (:value actual) plan/decode-value)) (pr-str inputs)))))
        (finally (sp/close storage))))))
