(ns perf
  "Compares a run's structural counters against the committed budgets.

   The model, and why it is counts and not milliseconds
   ===================================================
   `perf/budgets.edn` is to performance what `tools/visual-tests/**-snapshots/`
   is to the UI: a reference set, committed, reviewed in the diff, refreshed by
   an explicit `bb perf-update` that a human then commits.

   The difference is the tolerance. The visual baselines can afford
   `maxDiffPixelRatio: 0.02` because antialiasing noise is small and bounded.
   Wall-clock noise on this host is neither: `scripts/ci.clj` records two
   concurrent runs driving load average to 75 and timing out 9 of 17 checks, and
   `docs/PERF_NOTES.md` records a real optimisation measuring \"~5% — inside the
   run's std-dev, i.e. noise\". A wall-clock gate here would fail on its
   neighbours and pass on real 10% regressions. So this gate reads counts, which
   have no tolerance band at all: `1` is `1` on any machine, at any load.

   What belongs in the budget
   ==========================
   ONLY counters that are invariant to how many tests exist. `bb perf` runs over
   the whole unit suite, so a counter that ticks once per write — say
   `:registry/delta-recompile` — grows every time somebody adds a test. Gating it
   would fail honest PRs, and the fix (`bb perf-update`) would train everyone to
   re-baseline without reading, which is how a gate becomes a rubber stamp.

   So the budget holds the invariants: the fixture boots once no matter how many
   namespaces use it; a delta must never silently fall back to a full rebuild.
   Counters outside the budget are still reported — they are the trend data, and
   promoting one to a budget later is a one-line edit."
  (:require
    [babashka.fs :as fs]
    [clojure.edn :as edn]
    [clojure.pprint :as pp]
    [clojure.string :as str]))


(def ^:private budgets-path "perf/budgets.edn")


(def ^:private budgets-header
  "Re-emitted by `bb perf-update` on every write.

   It lives here, not in the file, because `pp/pprint` serialises the data
   structure and a comment is not data — the first `bb perf-update` would
   silently strip the file's entire rationale and leave a wall of numbers whose
   reason nobody could reconstruct. The `:why` strings survive because they ARE
   data; this header is the part that needed an owner."
  ";; The reference set `bb perf` gates against — the performance counterpart of
;; the committed visual baselines under tools/visual-tests/**-snapshots/.
;; Committed, reviewed in the diff, refreshed only by an explicit
;; `bb perf-update` that a human then commits.
;;
;; GENERATED by `bb perf-update` — edit :why freely (it is preserved), but this
;; header is re-emitted from scripts/perf.clj on every write.
;;
;; Every entry is a COUNT of a structural event, never a duration. That is the
;; whole design, not a simplification: `1` is `1` on a laptop, on ubuntu-latest,
;; and at the load average 75 that scripts/ci.clj once measured while timing out
;; 9 of 17 checks. docs/PERF_NOTES.md records a genuine optimisation measuring
;; \"~5% — inside the run's std-dev\"; counts have no std-dev. Wall-clock numbers
;; live in perf/runs/*.edn and are reported, never gated.
;;
;; ONLY invariants belong here — counters that do not move when somebody adds a
;; test. `:registry/delta-recompile` (346 across the unit suite) and
;; `:registry/rebuild` (107) grow with the namespace count; gating them would
;; fail honest PRs and train everyone to re-baseline without reading, which is
;; how a gate becomes a rubber stamp. They are reported as trend data instead.
;;
;; :max is a CEILING. Exceeding it fails `bb perf`, and the :why is what gets
;; printed — write it for whoever sees the failure with no context.

")


(def ^:private green "[32m")
(def ^:private red "[31m")
(def ^:private yellow "[33m")
(def ^:private dim "[2m")
(def ^:private bold "[1m")
(def ^:private reset "[0m")


(defn- read-edn
  [path]
  (when (fs/exists? path)
    (edn/read-string (slurp path))))


(defn- run-paths
  "Every per-suite report on disk. Each suite writes its own file, so a run of
   only the unit suite cannot silently satisfy an e2e budget."
  []
  (when (fs/exists? "perf/runs")
    (sort (map str (fs/glob "perf/runs" "*.edn")))))


(defn- suite-of
  [path]
  (keyword (fs/strip-ext (fs/file-name path))))


(defn- check-suite
  "→ {:suite :rows [{:event :n :max :ok? :why}] :missing-report?}.
   A budgeted counter absent from the report reads as 0 — an event that never
   fired. That is deliberate: `:registry/invalidate-full` never firing is the
   success case, and its counter is simply not in the map."
  [suite budget counters]
  {:suite suite
   :rows (vec (for [[event {:keys [max why]}] (sort-by key budget)
                    :let [n (get counters event 0)]]
                {:event event :n n :max max :ok? (<= n max) :why why}))})


(defn- print-suite!
  [{:keys [suite rows]} counters]
  (println (str "\n" bold (name suite) reset))
  (doseq [{:keys [event n max ok? why]} rows]
    (println (str "  " (if ok? (str green "✓" reset) (str red "✗" reset))
                  " " (format "%-38s" (str event))
                  (format "%4d" n) " / max " max))
    (when-not ok?
      (println (str "      " red why reset))))
  (let [budgeted (set (map :event rows))
        extra (sort (remove budgeted (keys counters)))]
    (when (seq extra)
      (println (str "  " dim "observed, not budgeted (trend only): "
                    (str/join ", " (map name extra)) reset)))))


(defn- update-budgets!
  "Rewrite every budgeted `:max` to what this run observed, keeping `:why`.
   Deliberately loud about raises: lowering a budget is a win being recorded,
   raising one is a regression being accepted, and the two must not look alike
   in a terminal. `tools/visual-tests/README.md` makes the same point about
   baselines — if it moved and you don't know why, that IS the finding."
  [budgets reports]
  (let [updated
        (reduce
          (fn [acc [suite counters]]
            (reduce
              (fn [acc' [event spec]]
                (let [n (get counters event 0)]
                  (when (> n (:max spec))
                    (println (str yellow "  ↑ RAISING " event ": " (:max spec)
                                  " → " n reset))
                    (println (str "      " (:why spec))))
                  (when (< n (:max spec))
                    (println (str green "  ↓ lowering " event ": " (:max spec)
                                  " → " n reset)))
                  (assoc-in acc' [suite event :max] n)))
              acc
              (get budgets suite)))
          budgets
          reports)]
    (spit budgets-path (str budgets-header (with-out-str (pp/pprint updated))))
    (println (str "\n" green "✓ wrote " budgets-path reset
                  " — review the diff before committing it."))))


(defn -main
  [& args]
  (let [update? (some #{"--update"} args)
        budgets (or (read-edn budgets-path) {})
        reports (into {} (for [p (run-paths)
                               :let [r (read-edn p)]
                               :when r]
                           [(suite-of p) (:counters r)]))]
    (cond
      (empty? reports)
      (do (println (str red "✗ no run reports under perf/runs/" reset))
          (println "  Produce one first — the suites write their own:")
          (println (str "      " bold "bb test-unit" reset "   → perf/runs/unit.edn"))
          (System/exit 2))

      update?
      (update-budgets! budgets reports)

      (empty? budgets)
      (do (println (str red "✗ no " budgets-path reset))
          (println (str "  Record the current readings as the reference set: "
                        bold "bb perf-update" reset))
          (System/exit 2))

      ;; Iterate the BUDGETS, not the reports. Iterating reports would silently
      ;; skip a budgeted suite whose run never happened — and report a green
      ;; gate for a suite it did not read. A budget with no measurement behind it
      ;; is the one outcome worse than a failing one, because it looks like
      ;; success. `bb perf` after `bb lint` is the obvious way to hit this.
      (seq (remove (set (keys reports)) (keys budgets)))
      (let [missing (remove (set (keys reports)) (keys budgets))]
        (println (str red "✗ no run report for budgeted suite(s): "
                      (str/join ", " (map name missing)) reset))
        (doseq [s missing]
          (println (str "      " (name s) " → " bold
                        (case s
                          :unit "bb test-unit"
                          :perf "bb test-perf"
                          (str "the " (name s) " suite"))
                        reset)))
        (System/exit 2))

      :else
      (let [results (for [[suite budget] (sort-by key budgets)
                          :let [counters (get reports suite)]]
                      (let [checked (check-suite suite budget counters)]
                        (print-suite! checked counters)
                        checked))
            failures (mapcat #(remove :ok? (:rows %)) results)]
        (if (seq failures)
          (do (println (str "\n" red bold "✗ perf FAILED" reset " — "
                            (count failures) " budget(s) exceeded"))
              (println (str dim "  These are counts, not timings: this did not fail"
                            " because the box was busy." reset))
              (println (str dim "  If the new count is genuinely correct: "
                            "bb perf-update, and say why in the commit." reset))
              (System/exit 1))
          (println (str "\n" green bold "✓ perf PASSED" reset
                        " — every structural budget held")))))))


(apply -main *command-line-args*)
