#!/usr/bin/env bb
;; tour-versions — the lesson-edition guard for the interactive tutorial.
;;
;; Every lesson in resources/packages/app/tour/fns.edn carries a `:version`
;; (its edition — see the header there). The version is what tells a reader
;; who finished a lesson that it changed under them, so it must move when the
;; lesson's FLOW moves. Nothing in the data can enforce that by itself, hence
;; this fingerprint: test/resources/tour-versions.edn records, per lesson
;; (keyed by `:slug` — the stable identity; a renumber moves no entry), the
;; version and a digest of the steps (title, body, target(s), check, creates).
;;
;;   bb tour-versions-check  -> (CI) every lesson's `:version` is a positive
;;                              integer, and the record holds every lesson at
;;                              exactly its current version and steps: steps
;;                              changed at the same version -> bump it; a
;;                              version the record does not hold (a bump, or a
;;                              new lesson, which starts at 1) -> re-record.
;;                              Otherwise a bump nobody recorded would let any
;;                              later step change at that version through.
;;                              A recorded lesson that vanished is fine (ids
;;                              retire).
;;   bb tour-versions        -> rewrite the record from the current lessons.
;;                              Run it after bumping a version — or after a
;;                              cosmetic edit that deliberately does NOT bump.
;;
;; The digest covers what a re-read would show the reader; `:chapter`, the
;; lesson title and `:requires` are catalogue metadata and stay out of it.

(ns tour-versions
  (:require
    [clojure.edn :as edn]
    [clojure.string :as str])
  (:import
    (java.security
      MessageDigest)))


(def ^:private lessons-edn "resources/packages/app/tour/fns.edn")
(def ^:private record-edn "test/resources/tour-versions.edn")


(defn- lessons
  []
  (let [pkg (edn/read-string (slurp lessons-edn))
        const (some #(when (= :_tour-lessons (:name %)) %) (:fns pkg))]
    ;; Editions belong to TOURED lessons — a text-only row (no steps) is a
    ;; pointer at its written lesson, nothing a reader finishes or re-reads.
    (filter :steps (get-in const [:args :value :lessons]))))


(defn- sha1
  [^String s]
  (let [d (MessageDigest/.digest (MessageDigest/getInstance "SHA-1")
                                 (String/.getBytes s "UTF-8"))]
    (str/join (map #(format "%02x" %) d))))


(defn- fingerprint
  [lesson]
  (sha1 (pr-str (mapv #(select-keys % [:title :body :target :targets :check :creates])
                      (:steps lesson)))))


(defn- lesson-key
  [l]
  (or (:slug l) (:id l)))


(defn- current-record
  []
  (into (sorted-map)
        (map (fn [l] [(lesson-key l) {:version (:version l) :steps (fingerprint l)}]))
        (lessons)))


(defn- write!
  []
  (let [rec (current-record)]
    (spit record-edn
          (str ";; Lesson editions of the interactive tutorial — GENERATED by `bb tour-versions`.\n"
               ";; Per lesson slug: the `:version` in app/tour/fns.edn and a digest of its steps.\n"
               ";; `bb tour-versions-check` fails when the steps changed but the version did\n"
               ";; not — bump `:version` (readers who finished the lesson are told to re-read)\n"
               ";; or, for a cosmetic edit, refresh this file — and when a lesson's version is\n"
               ";; not the one recorded here (refresh after every bump). See the fns.edn header.\n"
               ;; One entry per line, in cljstyle's shape (`{` and `}` hug the
               ;; first / last entry) so the record needs no `bb fix` after.
               "{"
               (str/join "\n " (map (fn [[id v]] (str (pr-str id) " " (pr-str v))) rec))
               "}\n"))
    (println (str "tour-versions: recorded " (count rec) " lessons → " record-edn))))


(defn problems
  "Every reason the lessons `ls` (each with its `:fingerprint`) disagree with
   the `recorded` edition map. A lesson passes only when the record holds it
   at its CURRENT version with its current steps: a record at another version
   (a bump nobody re-recorded) or no record at all (a new lesson) would let
   every later step change at that version through unnoticed."
  [ls recorded]
  (concat
    (for [l ls
          :when (not (and (integer? (:version l)) (pos? (:version l))))]
      (str "lesson " (:id l) ": :version must be a positive integer, got "
           (pr-str (:version l))))
    (for [l ls
          :let [was (get recorded (lesson-key l))
                v (:version l)]
          :when (and (integer? v) (pos? v))
          :when (not= was {:version v :steps (:fingerprint l)})]
      (cond
        (nil? was)
        (if (= 1 v)
          (str "lesson " (:id l) ": not in " record-edn " yet — run `bb tour-versions`"
               " to record edition 1")
          (str "lesson " (:id l) ": not in " record-edn " yet, so it should"
               " start at :version 1 (got " v ") — then `bb tour-versions`"))

        (not= (:version was) v)
        (str "lesson " (:id l) ": " record-edn " holds edition " (:version was)
             " but fns.edn says " v " — run `bb tour-versions` to record edition " v)

        :else
        (str "lesson " (:id l) ": the steps changed but :version is still "
             v " — bump it (readers who finished it are told to"
             " re-read), or `bb tour-versions` if the edit was cosmetic")))))


(defn- check
  []
  (let [ls (map #(assoc % :fingerprint (fingerprint %)) (lessons))
        recorded (try (edn/read-string (slurp record-edn)) (catch Exception _ {}))
        ps (problems ls recorded)]
    (if (seq ps)
      (do (doseq [p ps] (println (str "✗ " p)))
          (println (str "tour-versions-check FAILED (" (count ps) ")"))
          (System/exit 1))
      (println (str "✓ tour-versions-check: " (count ls) " lessons, each recorded"
                    " at its current :version and steps")))))


(case (first *command-line-args*)
  "write" (write!)
  "check" (check)
  ;; no argument: required as a library (scripts/tour_versions_test.clj)
  nil nil
  (do (println "usage: bb scripts/tour_versions.clj write|check") (System/exit 2)))
