#!/usr/bin/env bb
;; tour-versions — the lesson-edition guard for the interactive tutorial.
;;
;; Every lesson in resources/packages/app/tour/fns.edn carries a `:version`
;; (its edition — see the header there). The version is what tells a reader
;; who finished a lesson that it changed under them, so it must move when the
;; lesson's FLOW moves. Nothing in the data can enforce that by itself, hence
;; this fingerprint: test/resources/tour-versions.edn records, per lesson
;; (keyed by `:slug` — the stable identity; a renumber moves no entry), the
;; version and a digest of the steps (title, body, target(s), check, creates).
;;
;;   bb tour-versions-check  -> (CI) every lesson's `:version` is a positive
;;                              integer; where the steps' digest differs from
;;                              the recorded one, the version must differ too.
;;                              A lesson missing from the record is fine as long
;;                              as it is at version 1 (a new lesson); a recorded
;;                              lesson that vanished is fine too (ids retire).
;;   bb tour-versions        -> rewrite the record from the current lessons.
;;                              Run it after bumping a version — or after a
;;                              cosmetic edit that deliberately does NOT bump.
;;
;; The digest covers what a re-read would show the reader; `:chapter`, the
;; lesson title and `:requires` are catalogue metadata and stay out of it.

(ns tour-versions
  (:require
    [clojure.edn :as edn]
    [clojure.string :as str])
  (:import
    (java.security
      MessageDigest)))


(def ^:private lessons-edn "resources/packages/app/tour/fns.edn")
(def ^:private record-edn "test/resources/tour-versions.edn")


(defn- lessons
  []
  (let [pkg (edn/read-string (slurp lessons-edn))
        const (some #(when (= :_tour-lessons (:name %)) %) (:fns pkg))]
    ;; Editions belong to TOURED lessons — a text-only row (no steps) is a
    ;; pointer at its written lesson, nothing a reader finishes or re-reads.
    (filter :steps (get-in const [:args :value :lessons]))))


(defn- sha1
  [^String s]
  (let [d (MessageDigest/.digest (MessageDigest/getInstance "SHA-1")
                                 (String/.getBytes s "UTF-8"))]
    (str/join (map #(format "%02x" %) d))))


(defn- fingerprint
  [lesson]
  (sha1 (pr-str (mapv #(select-keys % [:title :body :target :targets :check :creates])
                      (:steps lesson)))))


(defn- lesson-key
  [l]
  (or (:slug l) (:id l)))


(defn- current-record
  []
  (into (sorted-map)
        (map (fn [l] [(lesson-key l) {:version (:version l) :steps (fingerprint l)}]))
        (lessons)))


(defn- write!
  []
  (let [rec (current-record)]
    (spit record-edn
          (str ";; Lesson editions of the interactive tutorial — GENERATED by `bb tour-versions`.\n"
               ";; Per lesson slug: the `:version` in app/tour/fns.edn and a digest of its steps.\n"
               ";; `bb tour-versions-check` fails when the steps changed but the version did\n"
               ";; not; bump `:version` (readers who finished the lesson are told to re-read)\n"
               ";; or, for a cosmetic edit, refresh this file. See the fns.edn header.\n"
               ;; One entry per line, in cljstyle's shape (`{` and `}` hug the
               ;; first / last entry) so the record needs no `bb fix` after.
               "{"
               (str/join "\n " (map (fn [[id v]] (str (pr-str id) " " (pr-str v))) rec))
               "}\n"))
    (println (str "tour-versions: recorded " (count rec) " lessons → " record-edn))))


(defn- check
  []
  (let [ls (lessons)
        recorded (try (edn/read-string (slurp record-edn)) (catch Exception _ {}))
        problems
        (concat
          (for [l ls
                :when (not (and (integer? (:version l)) (pos? (:version l))))]
            (str "lesson " (:id l) ": :version must be a positive integer, got "
                 (pr-str (:version l))))
          (for [l ls
                :let [was (get recorded (lesson-key l))
                      now (fingerprint l)]
                :when (and (integer? (:version l)) (pos? (:version l)))
                :when (if was
                        (and (not= (:steps was) now)
                             (= (:version was) (:version l)))
                        (not= 1 (:version l)))]
            (if was
              (str "lesson " (:id l) ": the steps changed but :version is still "
                   (:version l) " — bump it (readers who finished it are told to"
                   " re-read), or `bb tour-versions` if the edit was cosmetic")
              (str "lesson " (:id l) ": not in " record-edn " yet, so it should"
                   " start at :version 1 (got " (:version l) ") — or `bb tour-versions`"))))]
    (if (seq problems)
      (do (doseq [p problems] (println (str "✗ " p)))
          (println (str "tour-versions-check FAILED (" (count problems) ")"))
          (System/exit 1))
      (println (str "✓ tour-versions-check: " (count ls) " lessons, every changed"
                    " lesson carries a new :version")))))


(case (first *command-line-args*)
  "write" (write!)
  "check" (check)
  (do (println "usage: bb scripts/tour_versions.clj write|check") (System/exit 2)))
