(ns graphden.executor.runtime
  "Runtime helpers for the compiled executor.

   Impls generated by `defbase` use `resolve-arg` to access argument values.
   At runtime, the args map contains:

   - Literal values (from :value bindings or already-computed results).
   - 0-arity thunk fns (from ref bindings, generated at compile time to defer
     evaluation until the impl actually uses the arg).

   `resolve-arg` hides that distinction: if the arg is marked as a thunk it
   calls it; thunks are once-memoized (delay semantics — see `thunk`), so
   repeated reads of one arg see one value and never repeat an effect.

   `:fn`-typed args (higher-order) are NOT resolved. They enter the args map
   as already-wrapped callables and the impl (e.g. `map`, `reduce`) invokes
   them directly on each item.

   Thunk marker: metadata `{::thunk true}` on the fn. Using metadata rather
   than a custom record keeps everything as regular Clojure fns, which matters
   for tests (they can `(fn [] 42)` and wrap with `thunk` without importing
   types).")


(defn thunk
  "Wrap a 0-arity fn as a resolver thunk with ONCE (delay) semantics:
   the wrapped fn runs at most once, every later force returns the
   first result. A slot denotes ONE value per evaluation — the lazy
   model is delay-based (CLAUDE.md § Lazy Execution), and the
   closure-capture contract says captured args resolve once, invariant
   per wrap (docs/CLOSURE_CAPTURE.md).

   Once is load-bearing for correctness, not a cache: a ref thunk may
   wrap an EFFECTFUL subtree (`:_call-base-handler` → the whole app
   handler chain). Without once, a second force of the same thunk
   instance re-ran the handler inside one HTTP request whenever the
   per-execute call-cache key diverged — observed as the handler
   executing twice (the second run against an already-drained request
   body stream produced an internal 400 whose headers corrupted the
   encoded response). Once also makes the call-cache sound by
   construction: fa values ARE thunks, compared by identity inside the
   projected cache key, and with once a given thunk instance always
   denotes one value — so key equality implies input equality.

   Kept as a plain 0-arity fn (not a raw `delay`) so impls that read
   args raw (`((:body args))` — the closure-capture acceptance test)
   can still invoke it; the delay lives inside and provides
   thread-safe run-at-most-once."
  [f]
  (let [d (delay (f))]
    (with-meta (fn [] @d) {::thunk true})))


(defn thunk?
  [v]
  (and (fn? v) (::thunk (meta v))))


(defn resolve-arg
  "Return the resolved value for `arg-key` in `args`.

   Handles three cases:
   - `thunk?` — call it (compile-produced ref wrapping).
   - `IDeref` — `@` it (test code often passes `(delay …)` literals).
   - otherwise — return as-is."
  [args arg-key]
  (let [v (get args arg-key)]
    (cond
      (thunk? v) (v)
      (instance? clojure.lang.IDeref v) @v
      :else v)))


(defn hof-callable
  "Resolve an `:fn`-type arg into an invokable callable for HOF impls.

   - Compile-produced HOF wrapper (already a callable) → return as-is.
   - Raw fn-id (UUID, or an `IDeref` wrapping one from test code) →
     wrap via `make-single-arg-callable`.

   `make-single-arg-callable` is resolved lazily to avoid a require-cycle
   (runtime.clj sits below executor/interface.clj)."
  [args arg-key ctx]
  (let [v (get args arg-key)
        wrap-fn-id (fn [fn-id]
                     (let [make-callable (requiring-resolve 'graphden.executor.interface/make-single-arg-callable)]
                       (make-callable ctx fn-id)))]
    (cond
      (uuid? v)
      (wrap-fn-id v)

      (instance? clojure.lang.IDeref v)
      (let [fn-id @v]
        (if (uuid? fn-id)
          (wrap-fn-id fn-id)
          fn-id))

      :else v)))
