(ns graphden.executor.runtime
  "Runtime helpers for the compiled executor.

   Impls generated by `defbase` use `resolve-arg` to access argument values.
   At runtime, the args map contains:

   - Literal values (from :value bindings or already-computed results).
   - 0-arity thunk fns (from ref bindings, generated at compile time to defer
     evaluation until the impl actually uses the arg).

   `resolve-arg` hides that distinction: if the arg is marked as a thunk it
   calls it (once; thunks are not memoized — callers wanting memoization
   should arrange it themselves), otherwise returns as-is.

   `:fn`-typed args (higher-order) are NOT resolved. They enter the args map
   as already-wrapped callables and the impl (e.g. `map`, `reduce`) invokes
   them directly on each item.

   Thunk marker: metadata `{::thunk true}` on the fn. Using metadata rather
   than a custom record keeps everything as regular Clojure fns, which matters
   for tests (they can `(fn [] 42)` and wrap with `thunk` without importing
   types).")


(defn thunk
  "Wrap a 0-arity fn as a resolver thunk. `resolve-arg` will call it exactly
   once per use-site; multiple uses of the same arg in an impl body call the
   thunk multiple times. Memoize yourself if that matters (usually it doesn't
   — most impls reference each arg symbol once)."
  [f]
  (with-meta f {::thunk true}))


(defn thunk?
  [v]
  (and (fn? v) (::thunk (meta v))))


(defn resolve-arg
  "Return the resolved value for `arg-key` in `args`.

   Handles three cases:
   - `thunk?` — call it (compile.clj ref wrapping).
   - `IDeref` — `@` it (legacy queue.clj passes args as `SmartDelay`; kept
     through the impl migration so `defbase` impls run under both
     executors).
   - otherwise — return as-is."
  [args arg-key]
  (let [v (get args arg-key)]
    (cond
      (thunk? v) (v)
      (instance? clojure.lang.IDeref v) @v
      :else v)))


(defn hof-callable
  "Resolve an `:fn`-type arg into an invokable callable for HOF impls.

   - New compile model: value is already an HOF-wrapped Clojure fn
     (produced by `compile/hof-wrap`). Return as-is.
   - Legacy queue model path A: value is a `SmartDelay` whose deref
     yields a raw fn-id. Deref, then wrap via `make-single-arg-callable`.
   - Legacy queue model path B: the loader's `wrap-impl` deref'd the arg
     already before calling us, so we see a raw UUID directly. Same
     wrapping via `make-single-arg-callable`.

   `make-single-arg-callable` is resolved lazily to avoid a require-cycle
   (runtime.clj sits below executor/interface.clj). `ctx` is required for
   the legacy paths; new-executor callers pass whatever they like since
   those paths fall through."
  [args arg-key ctx]
  (let [v (get args arg-key)
        wrap-fn-id (fn [fn-id]
                     (let [make-callable (requiring-resolve 'graphden.executor.interface/make-single-arg-callable)]
                       (make-callable ctx fn-id)))]
    (cond
      (uuid? v)
      (wrap-fn-id v)

      (instance? clojure.lang.IDeref v)
      (let [fn-id @v]
        (if (uuid? fn-id)
          (wrap-fn-id fn-id)
          fn-id))

      :else v)))
