name: Dependency Update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * 1"  # Mondays at 9:00 AM UTC

jobs:
  update-deps:
    name: Update dependencies
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: nnichols/clojure-dependency-update-action@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          batch: "true"
          branch: "main"
          skips: "github-action"
